### ISSUE TITLE
Bug in corner_to_center_box3d function in utils.py

### ISSUE THREAD

**Issue by aseembehl** [qianguih/voxelnet#2]
Follwing Line 270 in utils.py

` x, y, z = np.sum(roi, axis=0) / 8`

should be replaced with the follwoing

```
x = np.sum(roi[:, 0], axis=0)/ 8
y = np.sum(roi[0:4, 1], axis=0)/ 4
z = np.sum(roi[:, 2], axis=0)/ 8
```

This makes sure that the x,y, z is the location of the bottom center of the bounding box.

**Comment by qianguih** [comment]
fixed in [4ede139](https://github.com/qianguih/voxelnet/commit/4ede13972d5fc51bd8e8f9cc5ed4e8311842ee44)
