### ISSUE TITLE
missing activation=False for p_map layer?

### ISSUE THREAD

**Issue by moskewcz** [qianguih/voxelnet#3]
( see issue jeasinema/VoxelNet-tensorflow#33 )

i'm having trouble understanding why the p_map layer doesn't have 'activation=False':

it's fed into a sigmoid, so if the activations are ReLU'd to be non-negative, it seems the objectness outputs will be limited to [.5,1]. maybe even if that's a bit wrong-ish, it doesn't much matter somehow? I.e. it messes up the gradient for the objectness somewhat, and compresses the range of confidences, but maybe that doesn't have a huge impact in the end?

it seems that, with the fixes in this repo, you're close to reproducing the original-paper-quality results, so i guess that means the impact can't be too large. BTW, thanks for sharing your efforts and fixes!

**Comment by qianguih** [comment]
You are right about the activation function. It should be disabled in this layer. BN should be disabled too.  Interestingly, they didn't impact the results. Anyway, they will be fixed in upcoming commit.

**Comment by qianguih** [comment]
fixed in [4ede139](https://github.com/qianguih/voxelnet/commit/4ede13972d5fc51bd8e8f9cc5ed4e8311842ee44)
