### ISSUE TITLE
About inference time

### ISSUE THREAD

**Issue by memoiry** [qianguih/voxelnet#4]
Hi, thanks for sharing your code, it's really wonderful.

It would be great to know what's the inference time of the code, the paper claimed a 225ms inference time where the voxel input feature computation takes 5ms, feature learning net takes 20ms, convolutional middle layers take 170ms and I'm a little curious about that. Can you please share that? thanks!

**Comment by qianguih** [comment]
I didn't do runtime benchmark. You should be able to easily do that by measure the runtime of [L285](https://github.com/qianguih/voxelnet/blob/master/model/model.py#L285) in `model.py`
