### ISSUE TITLE
KITTI/data/validation/label_2/ folder  is empty, how to train the voxelnet model?

### ISSUE THREAD

**Issue by luogyu7** [qianguih/voxelnet#92]
### when I try to run the voxelnet project , I have a few questions . 
**Firstly. the KITTI/data/validation/label_2/ folder  is empty**.To this question ,I copy the folder label_2 in  training folder to the validation folder . I am having a list access problem that is out of scope when I run the order 'python3 train.py --alpha 1 --beta 10'.
following is the picture. 
![1](https://user-images.githubusercontent.com/67385330/110492241-f8581b80-812c-11eb-83b3-d26d50a056ea.png)

and the load_index is added by myself for debuging. following picture is code position.

![2](https://user-images.githubusercontent.com/67385330/110493720-da3eeb00-812d-11eb-94dd-5cd370756455.png)

**secondly.** I saw some answers for splitting data sets, are they valid?I'm going to try it out, and if you can share it with anyone who has solved this problem, thank you very much.

The following is my setting pictures.
![config](https://user-images.githubusercontent.com/67385330/110493789-e88d0700-812d-11eb-9fbd-9859f3944a99.png)
![crop](https://user-images.githubusercontent.com/67385330/110493798-ea56ca80-812d-11eb-9e07-6d06f3dcae8b.png)
![data](https://user-images.githubusercontent.com/67385330/110493806-eb87f780-812d-11eb-975a-6666e875ec7a.png)
![training](https://user-images.githubusercontent.com/67385330/110493824-f04cab80-812d-11eb-8a65-63d6c240f13c.png)
![validation](https://user-images.githubusercontent.com/67385330/110493840-f5115f80-812d-11eb-814b-31d719df2a14.png)

Thanks very much.

**Comment by kasai2210** [comment]
Maybe you cropped the data incorrectly or while arranging the dataset according to the protocol you did some mistakes, I suggest you look into that first.

**Comment by luogyu7** [comment]
I found the issue ,I take some other image and label file in text folder. It works for me .
